Repository restincode/restincode, pull requests merged in 2019-07, with the labels that each got.

#38 README updates, contribution info
  README.md
Labels: Project

#46 Add Nick Jeremicah (Dr. Nick2000)
  images/Jeremicah_Nick.jpg
  memorials/jeremicah-nick.md
Labels: Add Person, People, Unreviewed

#48 Cohen joshua
  memorials/cohen-josh.md
Labels: Add Links, People

#54 Kaspersky kris
  images/Kaspersky_Kris.JPG
  images/Maxx_Redwine.jpg
  memorials/kaspersky-kris.md
  memorials/redwine-maxx.md
Labels: Add Person, Needs Review, People

#52 add Ryan Van Der Wall
  memorials/van-der-wall-ryan.md
Labels: Add Person, Needs Review, People

#51 add Nolan Berry
  memorials/berry-nolan.md
Labels: Add Person, People, Work in Progress

#55 Fix jhart's twitter
  memorials/hart-jon.md
Labels: Add Links, Needs Review, People
