Repository restincode/restincode, pull requests merged in 2023-07, with the labels that each got.

#196 Kelly Lum (Aloria)
  images/Kelly_Lum1.jpg
  images/Kelly_Lum2.jpg
  images/Kelly_Lum3.jpg
  images/Kelly_Lum4.jpg
  people/kellylum.json
  peoplelist.json
Labels: Add Data, Add Person, Needs Review

#202 Bruce Esquibel (Dr. Ripco)
  images/bruce_esquibel1.jpg
  images/bruce_esquibel2.jpg
  people/bruceesquibel.json
  peoplelist.json
Labels: People, Add Person, Needs Review

#214 chore(.pre-commit-config.yaml): remove unused pre-commit hook configu…
  .pre-commit-config.yaml
Labels: Project

#215 chore(CODEOWNERS): add CODEOWNERS file to specify code ownership and …
  CODEOWNERS
Labels: Project

#217 chore(Gemfile.lock): update async gem version from 2.6.2 to 2.6.3
  Gemfile.lock
Labels: Code

#220 fix(bradsmith.json): remove unused "birth" and "maintext" fields, add "obituary" and "affiliations" fields
  people/bradsmith.json
  people/chipmeadows.json
  people/karenKrystalia.json
Labels: BUG

#223 chore: add .pre-commit-config.yaml file
  .pre-commit-config.yaml
  README.md
Labels: Code

#224 chore(pre-commit-config.yaml): update pre-commit hooks and configuration
  .pre-commit-config.yaml
Labels: Code

#225 fix: add prettier.json checks to pre-commit
  .pre-commit-config.yaml
  config.json
  people/_template.json
  people/aaronswartz.json
  people/arjenkamphuis.json
  people/barnabyjack.json
  people/benbyer.json
  people/bill.json
  people/borisfloricic.json
  people/bradsmith.json
  people/brandenhancock.json
  people/bretmattingly.json
  people/bruceesquibel.json
  people/chipmeadows.json
  people/christianwright.json
  people/conorfaheylatrope.json
  people/darensenn.json
  people/davidjones.json
  people/devenfore.json
  people/donblumenthal.json
  people/ericchavez.json
  people/garyjames.json
  people/geoffreybennett.json
  people/ianmurdock.json
  people/jaimecochran.json
  people/jaydesdyson.json
  people/joeengressia.json
  people/joerogers.json
  people/jonathanstuart.json
  people/jonhart.json
  people/joshcohen.json
  people/karenKrystalia.json
  people/karlkoch.json
  people/kellylum.json
  people/kelvinwhite.json
  people/kriskaspersky.json
  people/larrytesler.json
  people/lensassaman.json
  people/maxxredwine.json
  people/michaelassante.json
  people/michaelhamelin.json
  people/mikekemp.json
  people/nickjeremicah.json
  people/nolanberry.json
  people/obsèquesdepaolo.json
  people/rebeccabace.json
  people/robertashby.json
  people/ryanvanderwall.json
  people/scottsard.json
  people/stevekirk.json
  people/terrencegareau.json
  people/tiffanyhinch.json
  peoplelist.json
Labels: Code

#226 chore(.pre-commit-config.yaml): update prettier hook to version 3.0.0
  .pre-commit-config.yaml
Labels: Code

#227 add curlylint to pre-commit hooks
  .pre-commit-config.yaml
  memorial.html
Labels: Code

#228 chore(index.html): update jQuery version to 3.7.0
  index.html
  memorial.html
Labels: Code, BUG

#229 chore(.pre-commit-config.yaml): enable autofixing pull-request commits by pre-commit.ci
  .pre-commit-config.yaml
Labels: Code

#210 fix(peoplelist.json): add Nolan Berry to the list of people
  images/Nolan_Berry.PNG
  people/nolanberry.json
  peoplelist.json
Labels: Add Data, Add Person

#212 feat: add profile for Christopher Fudge
  images/christopherfudge.jpg
  people/christopherfudge.json
  peoplelist.json
Labels: Add Person

#230 chore: enable end-of-file-fixer and trailing-whitespace pre-commit hooks
  .github/ISSUE_TEMPLATE/add-new-person-to-site.md
  .pre-commit-config.yaml
  CNAME
  Rakefile
Labels: Code

#231 chore(pre-commit-config.yaml): exclude 'CNAME' file from pre-commit checks
  .pre-commit-config.yaml
Labels: Code

#233 chore: set prettier for pre-commit
  .github/ISSUE_TEMPLATE/add-new-person-to-site.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/test_and_proof.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  index.html
  memorial.html
  style.css
Labels: Code
