Repository restincode/restincode, pull requests merged in 2023-08, with the labels that each got.

#234 fix(karenKrystalia.json): update death date to October 29, 1999
  people/karenKrystalia.json
Labels: Add Data

#235 chore(README.md): Remove html-check badge
  README.md
Labels: Project

#237 people: add John Horton Conway to peoplelist.json, johnhortonconway.json
  images/John_H_Conway_2005_(cropped).jpg
  people/johnhortonconway.json
  peoplelist.json
Labels: Add Person

#239 feat: add Aaron Testerman to peoplelist.json and aarontesterman.json
  people/aarontesterman.json
  peoplelist.json
Labels: Add Person

#240 Matthew D Smith
  people/matthewsmith.json
  peoplelist.json
Labels: Add Person

#242 Michael Hawley
  images/michael_hawley01.jpg
  images/michael_hawley02.jpg
  people/michaelhawley.json
  peoplelist.json
Labels: Add Person
